### ISSUE TITLE
Memory exhaustion caused by incorrect default value of "makeEqual"

### ISSUE THREAD

**Issue by lanshanyu** [mrdwab/splitstackshape#41] opened 2015-02-23 19:25 UTC
When specifying multiple concatenated columns to be parsed in a big rugged data (~half a million rows), R2.15 and R3 on Linux would report memory-related error message such as "cannot allocate memory" or "long vector not supported". The workaround that I found is to explicitly set makeEqual to False, as failing to do so would generate a large number of blank rows where the number of rows for each unique identifier equals the maximum number of delimiters found among all entries. I suspect this is the source of the memory exhaustion problem. 

This indicates that the default value of makeEqual, at least in my experience, is not False, as suggested by the document for the package.

Update: after coercing makeEqual to False, the result are totally off. Leaving makeEqual untouched creates memory problem for large dataset but produces the correct data after all NA rows are removed.

**Comment by mrdwab** [comment] 2018-03-31 06:13
Closing as I'm not able to reproduce. If a reproducible example can be provided, I'll reopen and look into it.

**Closed by mrdwab** 2018-03-31 06:13 UTC
